---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(flexdashboard)
```

```{r echo = FALSE}
data("instacart")
instacart =
  instacart |>
  filter(
    !is.na(order_dow),
    order_dow <= 5,  
    order_hour_of_day >= 8, 
    order_hour_of_day <= 18
  ) |>
  sample_n(1000) |>
  select(order_dow, order_hour_of_day, days_since_prior_order, reordered, aisle)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r echo = FALSE}
instacart |> 
  count(aisle)|>
  mutate(aisle = fct_reorder(aisle,n))|>
  plot_ly(
    x=~aisle, y =~n, color = ~aisle,
    type ="bar", colors = "viridis"
  )
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r warning = FALSE , echo = FALSE}
instacart |>
plot_ly(
    x = ~order_hour_of_day,
    y = ~days_since_prior_order,
    text = ~aisle,
    type = "scatter",
    mode = "markers",
    color = ~aisle,
    colors = "viridis",
    size = ~ifelse(reordered == 1, 12, 8),  
    sizes = c(8, 12),
    marker = list(opacity = 0.7, line = list(width = 0))
  ) |>
  layout(
    title = "Days since last order vs. Hour of the Day colored by Aisle",
    xaxis = list(title = "Order Hour of the Day"),
    yaxis = list(title = "Days Since Last Order"),
    colorbar = list(title = "Aisle"),
    legend = list(title = "Reordered Status")
  )
```

### Chart C

```{r echo = FALSE}
instacart |>
  mutate(aisle = fct_reorder(aisle, order_hour_of_day)) |>
  plot_ly(
    y = ~order_hour_of_day, x =~aisle, color = ~aisle,
    type = "violin", colors = "viridis"
  )
```

